name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.23
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go install golang.org/x/tools/cmd/cover@latest
        go install github.com/mattn/goveralls@latest

    - name: Test
      run: go test -v -covermode=count -coverprofile=coverage.out ./...

    - name: Coveralls
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN
      # Do not run on pull requests since we don't have the token available there.
      if: ${{ github.event_name != 'pull_request' }}

    - name: check for go vulnerabilities
      uses: Templum/govulncheck-action@main
      with:
        go-version: 1.23
